//
//  ContentView.swift
//  Ant Colony Simulation
//
//  Individual-based ant colony model.
//  Colony behavior emerges from individual ant decisions,
//  food availability, pheromone dynamics, energy balance,
//  reproduction, mortality, and local interactions.
//

import SwiftUI
import Foundation
import Combine

// MARK: - Food

enum FoodType: CaseIterable {
    case seed
    case fruit
    case insect
    case nectar

    var displayName: String {
        switch self {
        case .seed: return "Seed"
        case .fruit: return "Fruit"
        case .insect: return "Insect"
        case .nectar: return "Nectar"
        }
    }

    var symbol: String {
        switch self {
        case .seed: return "S"
        case .fruit: return "F"
        case .insect: return "I"
        case .nectar: return "N"
        }
    }

    var energyPerUnit: Double {
        switch self {
        case .seed: return 5.0
        case .fruit: return 10.0
        case .insect: return 18.0
        case .nectar: return 7.0
        }
    }

    var attraction: Double {
        switch self {
        case .seed: return 0.8
        case .fruit: return 1.0
        case .insect: return 1.6
        case .nectar: return 1.1
        }
    }

    var collectionDifficulty: Double {
        switch self {
        case .seed: return 0.8
        case .fruit: return 1.0
        case .insect: return 1.4
        case .nectar: return 0.9
        }
    }
}

// MARK: - Terrain

enum Terrain {
    case empty
    case nest
    case tunnel
    case food
    case obstacle
}

// MARK: - Ant State

enum AntState: String {
    case searching
    case returning
    case resting
    case exploring
}

// MARK: - Food Source

struct FoodSource: Identifiable {
    let id = UUID()

    var x: Int
    var y: Int

    var type: FoodType
    var amount: Double

    var depleted: Bool {
        amount <= 0.01
    }
}

// MARK: - Ant

struct Ant: Identifiable {
    let id = UUID()

    var x: Double
    var y: Double

    var state: AntState = .searching

    var energy: Double = 100.0
    var carriedFood: Double = 0.0
    var carriedFoodType: FoodType?

    var age: Int = 0

    var directionX: Double = 0.0
    var directionY: Double = 0.0

    // A small amount of memory allows ants to remember
    // productive locations without giving them global knowledge.
    var rememberedFoodX: Double?
    var rememberedFoodY: Double?

    // Individual sensitivity differences make the colony
    // less deterministic.
    var pheromoneSensitivity: Double = 1.0
    var explorationBias: Double = 1.0

    var hasFood: Bool {
        carriedFood > 0.01
    }
}

// MARK: - Colony Cell

struct ColonyCell {
    var terrain: Terrain = .empty

    // Scalar pheromone fields.
    var foodPheromone: Double = 0.0
    var nestPheromone: Double = 0.0

    // Nest construction.
    var construction: Double = 0.0
    var nestStrength: Double = 0.0

    // Local density generated by actual ants.
    var antCount: Int = 0

    // Environmental stress.
    var threat: Double = 0.0
}

// MARK: - Simulation

@MainActor
final class AntColonySimulation: ObservableObject {

    // MARK: Published State

    @Published var cells: [ColonyCell]

    @Published var ants: [Ant] = []

    @Published var foodSources: [FoodSource] = []

    @Published var generation: Int = 0

    @Published var colonyEnergy: Double

    @Published var foodCollected: Double = 0.0

    @Published var foodCreated: Double = 0.0

    @Published var colonyAlive: Bool = true

    @Published var births: Int = 0

    @Published var deaths: Int = 0

    @Published var paused: Bool = false

    // MARK: World

    let width: Int
    let height: Int

    let nestCenterX: Int
    let nestCenterY: Int

    let initialPopulation = 250
    let maximumPopulation = 1000

    // MARK: Simulation Timing

    private var nextFoodGeneration: Int = 1

    private let maximumFoodSources = 25

    // MARK: Initialization

    init(width: Int = 100, height: Int = 65) {

        self.width = width
        self.height = height

        self.nestCenterX = width / 2
        self.nestCenterY = height / 2

        self.cells = Array(
            repeating: ColonyCell(),
            count: width * height
        )

        // Initial energy is proportional to colony size.
        self.colonyEnergy = Double(initialPopulation) * 8.0

        buildWorld()

        createInitialColony()

        // Food exists immediately.
        createInitialFood()
    }

    // MARK: World Construction

    private func buildWorld() {

        for y in 0..<height {
            for x in 0..<width {

                let dx = Double(x - nestCenterX)
                let dy = Double(y - nestCenterY)

                let distance = sqrt(dx * dx + dy * dy)

                let index = indexFor(x, y)

                if distance <= 6.0 {
                    cells[index].terrain = .nest
                    cells[index].nestStrength = 1.0
                }
                else if abs(dx) < 1.5 || abs(dy) < 1.5 {
                    cells[index].terrain = .tunnel
                    cells[index].construction = 1.0
                }
            }
        }

        // Environmental obstacles.
        var obstaclesCreated = 0

        while obstaclesCreated < 85 {

            let x = Int.random(in: 3..<(width - 3))
            let y = Int.random(in: 3..<(height - 3))

            let dx = Double(x - nestCenterX)
            let dy = Double(y - nestCenterY)

            let distance = sqrt(dx * dx + dy * dy)

            guard distance > 13 else {
                continue
            }

            let index = indexFor(x, y)

            guard cells[index].terrain == .empty else {
                continue
            }

            cells[index].terrain = .obstacle
            obstaclesCreated += 1
        }
    }

    // MARK: Initial Colony

    private func createInitialColony() {

        ants.reserveCapacity(maximumPopulation)

        for _ in 0..<initialPopulation {

            let angle = Double.random(in: 0...(Double.pi * 2))

            let radius =
                sqrt(Double.random(in: 0...1)) * 8.0

            let x =
                Double(nestCenterX) +
                cos(angle) * radius

            let y =
                Double(nestCenterY) +
                sin(angle) * radius

            let ant = Ant(
                x: clamp(x, 1, Double(width - 2)),
                y: clamp(y, 1, Double(height - 2)),
                state: .resting,
                energy: Double.random(in: 75...100),
                pheromoneSensitivity: Double.random(in: 0.75...1.25),
                explorationBias: Double.random(in: 0.75...1.25)
            )

            ants.append(ant)
        }
    }

    // MARK: Initial Food

    private func createInitialFood() {

        for _ in 0..<12 {
            createFoodSource()
        }

        nextFoodGeneration =
            generation + Int.random(in: 12...25)
    }

    // MARK: Automatic Food

    private func generateFoodIfNeeded() {

        guard generation >= nextFoodGeneration else {
            return
        }

        guard foodSources.count < maximumFoodSources else {
            nextFoodGeneration =
                generation + Int.random(in: 8...18)
            return
        }

        let populationDemand =
            max(
                1,
                min(
                    5,
                    Int(
                        ceil(
                            Double(max(ants.count, 1)) /
                            Double(initialPopulation)
                        )
                    )
                )
            )

        let lower = max(1, populationDemand - 1)
        let upper = min(5, populationDemand + 1)

        let sourceCount =
            Int.random(in: lower...upper)

        for _ in 0..<sourceCount {

            guard foodSources.count < maximumFoodSources else {
                break
            }

            createFoodSource()
        }

        // Larger colonies generally encounter new food
        // more frequently because they occupy more area.
        let intervalLow =
            max(7, 20 - ants.count / 80)

        let intervalHigh =
            max(intervalLow + 3, 32 - ants.count / 60)

        nextFoodGeneration =
            generation + Int.random(
                in: intervalLow...intervalHigh
            )
    }

    private func createFoodSource() {

        guard let location = randomFoodLocation() else {
            return
        }

        let type = chooseFoodType()

        let populationFactor =
            min(
                2.0,
                max(
                    0.75,
                    Double(max(ants.count, 1)) /
                    Double(initialPopulation)
                )
            )

        let amount: Double

        switch type {

        case .seed:
            amount =
                Double.random(in: 30...85) *
                populationFactor

        case .fruit:
            amount =
                Double.random(in: 15...50) *
                populationFactor

        case .insect:
            amount =
                Double.random(in: 5...22) *
                populationFactor

        case .nectar:
            amount =
                Double.random(in: 20...65) *
                populationFactor
        }

        let source = FoodSource(
            x: location.x,
            y: location.y,
            type: type,
            amount: amount
        )

        foodSources.append(source)

        let index = indexFor(
            location.x,
            location.y
        )

        cells[index].terrain = .food

        foodCreated += amount
    }

    // The computer chooses food type based on colony energy
    // and randomness. Ants do not know this information globally.
    private func chooseFoodType() -> FoodType {

        let energyPerAnt =
            colonyEnergy /
            Double(max(ants.count, 1))

        let roll = Double.random(in: 0..<1)

        if energyPerAnt < 4 {

            if roll < 0.40 {
                return .insect
            }

            if roll < 0.70 {
                return .fruit
            }

            if roll < 0.88 {
                return .nectar
            }

            return .seed
        }

        if energyPerAnt < 8 {

            if roll < 0.30 {
                return .insect
            }

            if roll < 0.55 {
                return .fruit
            }

            if roll < 0.80 {
                return .nectar
            }

            return .seed
        }

        return FoodType.allCases.randomElement()!
    }

    private func randomFoodLocation()
        -> (x: Int, y: Int)? {

        for _ in 0..<100 {

            let x =
                Int.random(in: 4..<(width - 4))

            let y =
                Int.random(in: 4..<(height - 4))

            let dx =
                Double(x - nestCenterX)

            let dy =
                Double(y - nestCenterY)

            let distance =
                sqrt(dx * dx + dy * dy)

            guard distance > 12 else {
                continue
            }

            let index = indexFor(x, y)

            guard cells[index].terrain == .empty else {
                continue
            }

            return (x, y)
        }

        return nil
    }

    // MARK: Simulation Step

    func step() {

        guard colonyAlive else {
            return
        }

        generation += 1

        generateFoodIfNeeded()

        updateLocalPopulationDensity()

        moveAnts()

        constructNest()

        evaporatePheromones()

        consumeColonyEnergy()

        populationDynamics()

        removeDepletedFood()

        evaluateColony()
    }

    // MARK: Local Density

    private func updateLocalPopulationDensity() {

        for i in cells.indices {
            cells[i].antCount = 0
        }

        for ant in ants {

            let x =
                Int(ant.x.rounded())

            let y =
                Int(ant.y.rounded())

            guard x >= 0,
                  x < width,
                  y >= 0,
                  y < height
            else {
                continue
            }

            cells[indexFor(x, y)].antCount += 1
        }
    }

    // MARK: Ant Movement

    private func moveAnts() {

        for i in ants.indices {

            ants[i].age += 1

            let localDensity =
                localCrowding(
                    atX: ants[i].x,
                    y: ants[i].y
                )

            let populationPressure =
                min(
                    1.0,
                    Double(ants.count) /
                    Double(maximumPopulation)
                )

            let stateCost =
                movementCost(
                    state: ants[i].state,
                    density: localDensity,
                    populationPressure: populationPressure
                )

            ants[i].energy -= stateCost

            if ants[i].energy <= 0 {
                continue
            }

            // Resting ants recover slowly in the nest.
            if ants[i].state == .resting {

                if isInsideNest(
                    x: ants[i].x,
                    y: ants[i].y
                ) {

                    let recovery =
                        min(
                            1.0,
                            colonyEnergy /
                            Double(max(ants.count, 1))
                        )

                    ants[i].energy +=
                        recovery * 0.12
                }

                // Resting eventually becomes exploration.
                if Double.random(in: 0...1) < 0.025 {
                    ants[i].state = .searching
                }

                continue
            }

            // A food-carrying ant always tries to return home.
            if ants[i].hasFood {

                ants[i].state = .returning

                moveReturningAnt(index: i)

                continue
            }

            // Check whether food is immediately available.
            if let foodIndex =
                foodAt(
                    x: ants[i].x,
                    y: ants[i].y,
                    radius: 1.5
                ) {

                collectFood(
                    antIndex: i,
                    foodIndex: foodIndex
                )

                continue
            }

            // Searchers use local information.
            moveSearchingAnt(index: i)
        }

        removeDeadAnts()
    }

    // MARK: Searching

    private func moveSearchingAnt(index: Int) {

        guard ants.indices.contains(index) else {
            return
        }

        let ant = ants[index]

        let populationPressure =
            min(
                1.0,
                Double(ants.count) /
                Double(maximumPopulation)
            )

        let exploration =
            max(
                0.08,
                ant.explorationBias *
                (
                    1.0 -
                    populationPressure * 0.65
                )
            )

        let trailWeight =
            ant.pheromoneSensitivity *
            (
                0.8 +
                populationPressure * 1.6
            )

        var vx = 0.0
        var vy = 0.0

        // 1. Nearby food.
        let foodVector =
            foodDirection(
                for: ant
            )

        vx += foodVector.x * 3.0
        vy += foodVector.y * 3.0

        // 2. Local pheromone gradient.
        let pheromone =
            pheromoneDirection(
                for: ant
            )

        vx +=
            pheromone.x *
            trailWeight

        vy +=
            pheromone.y *
            trailWeight

        // 3. Memory of previously discovered food.
        if let memoryX = ant.rememberedFoodX,
           let memoryY = ant.rememberedFoodY {

            let dx = memoryX - ant.x
            let dy = memoryY - ant.y

            let distance =
                sqrt(dx * dx + dy * dy)

            if distance > 0.5 &&
               distance < 35 {

                vx +=
                    (dx / distance) *
                    0.35

                vy +=
                    (dy / distance) *
                    0.35
            }
        }

        // 4. Nest avoidance while exploring.
        let nestDistance =
            distanceFromNest(
                x: ant.x,
                y: ant.y
            )

        if nestDistance < 9 {

            let dx =
                ant.x -
                Double(nestCenterX)

            let dy =
                ant.y -
                Double(nestCenterY)

            let distance =
                max(
                    0.001,
                    sqrt(dx * dx + dy * dy)
                )

            vx +=
                (dx / distance) *
                0.6

            vy +=
                (dy / distance) *
                0.6
        }

        // 5. Local crowding avoidance.
        let crowd =
            crowdingDirection(
                for: ant
            )

        vx +=
            crowd.x *
            (
                0.5 +
                populationPressure * 1.5
            )

        vy +=
            crowd.y *
            (
                0.5 +
                populationPressure * 1.5
            )

        // 6. Individual stochastic exploration.
        vx +=
            Double.random(in: -1...1) *
            exploration

        vy +=
            Double.random(in: -1...1) *
            exploration

        let direction =
            normalized(
                x: vx,
                y: vy
            )

        let speed =
            max(
                0.18,
                0.48 -
                localCrowding(
                    atX: ant.x,
                    y: ant.y
                ) * 0.025
            )

        let moved =
            moveAntSafely(
                index: index,
                directionX: direction.x,
                directionY: direction.y,
                speed: speed
            )

        if !moved {
            ants[index].directionX =
                -ants[index].directionX

            ants[index].directionY =
                -ants[index].directionY
        }

        if Double.random(in: 0...1) < 0.003 {
            ants[index].state = .exploring
        }
        else {
            ants[index].state = .searching
        }
    }

    // MARK: Returning

    private func moveReturningAnt(index: Int) {

        let ant = ants[index]

        let dx =
            Double(nestCenterX) -
            ant.x

        let dy =
            Double(nestCenterY) -
            ant.y

        let distance =
            max(
                0.001,
                sqrt(dx * dx + dy * dy)
            )

        var vx =
            dx / distance

        var vy =
            dy / distance

        // Returning ants prefer the nest pheromone gradient.
        let trail =
            nestDirection(
                for: ant
            )

        vx =
            vx * 0.75 +
            trail.x * 0.25

        vy =
            vy * 0.75 +
            trail.y * 0.25

        let direction =
            normalized(
                x: vx,
                y: vy
            )

        let speed = 0.60

        _ = moveAntSafely(
            index: index,
            directionX: direction.x,
            directionY: direction.y,
            speed: speed
        )

        // Returning ants lay a nest-directed trail.
        let x =
            Int(ants[index].x.rounded())

        let y =
            Int(ants[index].y.rounded())

        if x >= 0,
           x < width,
           y >= 0,
           y < height {

            let cellIndex =
                indexFor(x, y)

            cells[cellIndex].foodPheromone =
                min(
                    25.0,
                    cells[cellIndex].foodPheromone +
                    0.18
                )

            cells[cellIndex].nestPheromone =
                min(
                    25.0,
                    cells[cellIndex].nestPheromone +
                    0.10
                )
        }

        if isInsideNest(
            x: ants[index].x,
            y: ants[index].y
        ) {

            deliverFood(
                antIndex: index
            )
        }
    }

    // MARK: Movement Safety

    private func moveAntSafely(
        index: Int,
        directionX: Double,
        directionY: Double,
        speed: Double
    ) -> Bool {

        let oldX = ants[index].x
        let oldY = ants[index].y

        let candidateX =
            oldX +
            directionX * speed

        let candidateY =
            oldY +
            directionY * speed

        if isWalkable(
            x: candidateX,
            y: candidateY
        ) {

            ants[index].x = candidateX
            ants[index].y = candidateY

            ants[index].directionX =
                directionX

            ants[index].directionY =
                directionY

            return true
        }

        // Try rotated directions if an obstacle blocks
        // the preferred direction.
        let alternatives: [(Double, Double)] = [
            (-directionY, directionX),
            (directionY, -directionX),
            (-directionX, -directionY)
        ]

        for alternative in alternatives {

            let nx =
                oldX +
                alternative.0 *
                speed

            let ny =
                oldY +
                alternative.1 *
                speed

            if isWalkable(
                x: nx,
                y: ny
            ) {

                ants[index].x = nx
                ants[index].y = ny

                ants[index].directionX =
                    alternative.0

                ants[index].directionY =
                    alternative.1

                return true
            }
        }

        return false
    }

    private func isWalkable(
        x: Double,
        y: Double
    ) -> Bool {

        guard x >= 1,
              x < Double(width - 1),
              y >= 1,
              y < Double(height - 1)
        else {
            return false
        }

        let ix =
            Int(x.rounded())

        let iy =
            Int(y.rounded())

        return cells[indexFor(ix, iy)].terrain
            != .obstacle
    }

    // MARK: Food Detection

    private func foodDirection(
        for ant: Ant
    ) -> (x: Double, y: Double) {

        var resultX = 0.0
        var resultY = 0.0

        let sensoryRadius = 22.0

        for source in foodSources {

            let dx =
                Double(source.x) -
                ant.x

            let dy =
                Double(source.y) -
                ant.y

            let distance =
                sqrt(dx * dx + dy * dy)

            guard distance > 0.01,
                  distance < sensoryRadius
            else {
                continue
            }

            let amountFactor =
                min(
                    3.0,
                    max(
                        0.2,
                        source.amount / 20.0
                    )
                )

            let weight =
                source.type.attraction *
                amountFactor /
                max(distance, 1.0)

            resultX +=
                (dx / distance) *
                weight

            resultY +=
                (dy / distance) *
                weight
        }

        return normalized(
            x: resultX,
            y: resultY
        )
    }

    private func pheromoneDirection(
        for ant: Ant
    ) -> (x: Double, y: Double) {

        let cx =
            Int(ant.x.rounded())

        let cy =
            Int(ant.y.rounded())

        var bestValue = 0.0

        var bestX = 0
        var bestY = 0

        for dy in -2...2 {
            for dx in -2...2 {

                if dx == 0 && dy == 0 {
                    continue
                }

                let x = cx + dx
                let y = cy + dy

                guard x >= 0,
                      x < width,
                      y >= 0,
                      y < height
                else {
                    continue
                }

                let value =
                    cells[indexFor(x, y)]
                    .foodPheromone

                if value > bestValue {

                    bestValue = value
                    bestX = dx
                    bestY = dy
                }
            }
        }

        return normalized(
            x: Double(bestX),
            y: Double(bestY)
        )
    }

    // MARK: Nest Trail

    private func nestDirection(
        for ant: Ant
    ) -> (x: Double, y: Double) {

        let cx =
            Int(ant.x.rounded())

        let cy =
            Int(ant.y.rounded())

        var vx = 0.0
        var vy = 0.0

        for dy in -2...2 {
            for dx in -2...2 {

                if dx == 0 && dy == 0 {
                    continue
                }

                let x = cx + dx
                let y = cy + dy

                guard x >= 0,
                      x < width,
                      y >= 0,
                      y < height
                else {
                    continue
                }

                let value =
                    cells[indexFor(x, y)]
                    .nestPheromone

                let distance =
                    sqrt(
                        Double(dx * dx + dy * dy)
                    )

                guard distance > 0 else {
                    continue
                }

                vx +=
                    Double(dx) /
                    distance *
                    value

                vy +=
                    Double(dy) /
                    distance *
                    value
            }
        }

        return normalized(
            x: vx,
            y: vy
        )
    }

    // MARK: Crowding

    private func localCrowding(
        atX x: Double,
        y: Double
    ) -> Double {

        let cx =
            Int(x.rounded())

        let cy =
            Int(y.rounded())

        var count = 0

        for dy in -2...2 {
            for dx in -2...2 {

                let nx = cx + dx
                let ny = cy + dy

                guard nx >= 0,
                      nx < width,
                      ny >= 0,
                      ny < height
                else {
                    continue
                }

                count +=
                    cells[indexFor(nx, ny)].antCount
            }
        }

        return min(
            3.0,
            Double(count) / 12.0
        )
    }

    private func crowdingDirection(
        for ant: Ant
    ) -> (x: Double, y: Double) {

        let cx =
            Int(ant.x.rounded())

        let cy =
            Int(ant.y.rounded())

        var vx = 0.0
        var vy = 0.0

        for dy in -2...2 {
            for dx in -2...2 {

                if dx == 0 && dy == 0 {
                    continue
                }

                let x = cx + dx
                let y = cy + dy

                guard x >= 0,
                      x < width,
                      y >= 0,
                      y < height
                else {
                    continue
                }

                let count =
                    cells[indexFor(x, y)].antCount

                guard count > 0 else {
                    continue
                }

                let distance =
                    sqrt(
                        Double(dx * dx + dy * dy)
                    )

                guard distance > 0 else {
                    continue
                }

                // Move away from dense neighboring cells.
                vx -=
                    Double(dx) /
                    distance *
                    Double(count)

                vy -=
                    Double(dy) /
                    distance *
                    Double(count)
            }
        }

        return normalized(
            x: vx,
            y: vy
        )
    }

    // MARK: Food Collection

    private func foodAt(
        x: Double,
        y: Double,
        radius: Double
    ) -> Int? {

        var closest: Int?
        var closestDistance = Double.infinity

        for index in foodSources.indices {

            let source =
                foodSources[index]

            let dx =
                Double(source.x) - x

            let dy =
                Double(source.y) - y

            let distance =
                sqrt(dx * dx + dy * dy)

            if distance <= radius &&
               distance < closestDistance &&
               !source.depleted {

                closest = index
                closestDistance = distance
            }
        }

        return closest
    }

    private func collectFood(
        antIndex: Int,
        foodIndex: Int
    ) {

        guard foodSources.indices.contains(foodIndex) else {
            return
        }

        let available =
            foodSources[foodIndex].amount

        guard available > 0 else {
            return
        }

        let type =
            foodSources[foodIndex].type

        let collectionAmount =
            min(
                4.0 / type.collectionDifficulty,
                available
            )

        foodSources[foodIndex].amount -=
            collectionAmount

        ants[antIndex].carriedFood +=
            collectionAmount

        ants[antIndex].carriedFoodType =
            type

        ants[antIndex].state =
            .returning

        ants[antIndex].rememberedFoodX =
            Double(foodSources[foodIndex].x)

        ants[antIndex].rememberedFoodY =
            Double(foodSources[foodIndex].y)

        // Strong reinforcement at a successful food location.
        let x =
            foodSources[foodIndex].x

        let y =
            foodSources[foodIndex].y

        let index =
            indexFor(x, y)

        cells[index].foodPheromone =
            min(
                25.0,
                cells[index].foodPheromone +
                3.0 *
                type.attraction
            )
    }

    // MARK: Food Delivery

    private func deliverFood(
        antIndex: Int
    ) {

        guard ants[antIndex].hasFood else {
            ants[antIndex].state = .resting
            return
        }

        let amount =
            ants[antIndex].carriedFood

        let type =
            ants[antIndex].carriedFoodType
            ?? .seed

        let energyDelivered =
            amount *
            type.energyPerUnit

        // Most collected food becomes colony energy.
        colonyEnergy +=
            energyDelivered * 0.85

        foodCollected += amount

        ants[antIndex].carriedFood = 0
        ants[antIndex].carriedFoodType = nil

        ants[antIndex].energy =
            min(
                100,
                ants[antIndex].energy + 25
            )

        ants[antIndex].state =
            .resting

        // Strong nest reinforcement.
        let x =
            Int(ants[antIndex].x.rounded())

        let y =
            Int(ants[antIndex].y.rounded())

        if x >= 0,
           x < width,
           y >= 0,
           y < height {

            let index =
                indexFor(x, y)

            cells[index].nestPheromone =
                min(
                    25,
                    cells[index].nestPheromone + 2.0
                )
        }
    }

    // MARK: Energy

    private func movementCost(
        state: AntState,
        density: Double,
        populationPressure: Double
    ) -> Double {

        let base: Double

        switch state {

        case .searching:
            base = 0.32

        case .exploring:
            base = 0.42

        case .returning:
            base = 0.28

        case .resting:
            base = 0.05
        }

        return base *
            (
                1.0 +
                density * 0.10 +
                populationPressure * 0.15
            )
    }

    private func consumeColonyEnergy() {

        let population =
            Double(ants.count)

        let activeAnts =
            Double(
                ants.filter {
                    $0.state != .resting
                }.count
            )

        let metabolicCost =
            population * 0.055

        let activityCost =
            activeAnts * 0.025

        let constructionCost =
            cells.reduce(0.0) {
                result, cell in
                result +
                (
                    cell.construction > 0.5
                    ? 0.002
                    : 0
                )
            }

        colonyEnergy -=
            metabolicCost +
            activityCost +
            constructionCost

        colonyEnergy =
            max(0, colonyEnergy)
    }

    // MARK: Population Dynamics

    private func populationDynamics() {

        guard generation % 20 == 0 else {
            return
        }

        let population =
            Double(ants.count)

        guard population > 0 else {
            return
        }

        let energyPerAnt =
            colonyEnergy / population

        // Reproduction is resource dependent.
        // There is no arbitrary population threshold controlling births.
        if energyPerAnt > 8.0 &&
           colonyEnergy > population * 7.0 &&
           ants.count < maximumPopulation {

            let surplus =
                max(
                    0,
                    energyPerAnt - 8.0
                )

            let reproductionRate =
                min(
                    0.035,
                    0.008 +
                    surplus * 0.0015
                )

            let requestedBirths =
                max(
                    1,
                    Int(
                        population *
                        reproductionRate
                    )
                )

            let availableSlots =
                maximumPopulation -
                ants.count

            let birthCount =
                min(
                    requestedBirths,
                    availableSlots
                )

            let birthCost =
                Double(birthCount) * 25.0

            guard colonyEnergy > birthCost else {
                return
            }

            for _ in 0..<birthCount {

                let angle =
                    Double.random(
                        in: 0...(Double.pi * 2)
                    )

                let radius =
                    Double.random(in: 0.5...5.5)

                let ant = Ant(
                    x:
                        Double(nestCenterX) +
                        cos(angle) * radius,
                    y:
                        Double(nestCenterY) +
                        sin(angle) * radius,
                    state: .resting,
                    energy: Double.random(in: 75...95),
                    pheromoneSensitivity:
                        Double.random(in: 0.8...1.2),
                    explorationBias:
                        Double.random(in: 0.8...1.2)
                )

                ants.append(ant)
            }

            colonyEnergy -= birthCost

            births += birthCount
        }

        // Colony-wide resource shortage increases mortality.
        if energyPerAnt < 1.5 {

            let deathsThisCycle =
                min(
                    4,
                    ants.count
                )

            killWeakestAnts(
                count: deathsThisCycle
            )
        }
    }

    private func removeDeadAnts() {

        let before =
            ants.count

        ants.removeAll {
            $0.energy <= 0 ||
            $0.age > 6000
        }

        let removed =
            before - ants.count

        if removed > 0 {
            deaths += removed
        }
    }

    private func killWeakestAnts(
        count: Int
    ) {

        guard !ants.isEmpty else {
            return
        }

        let sorted =
            ants.indices.sorted {
                ants[$0].energy <
                ants[$1].energy
            }

        let indexesToRemove =
            Set(
                sorted.prefix(
                    min(
                        count,
                        sorted.count
                    )
                )
            )

        let before =
            ants.count

        ants = ants.enumerated()
            .filter {
                !indexesToRemove.contains($0.offset)
            }
            .map {
                $0.element
            }

        deaths +=
            before - ants.count
    }

    // MARK: Nest Construction

    private func constructNest() {

        for i in cells.indices {

            guard cells[i].terrain == .empty ||
                  cells[i].terrain == .tunnel
            else {
                continue
            }

            let x =
                i % width

            let y =
                i / width

            let localAnts =
                cells[i].antCount

            guard localAnts > 0 else {
                continue
            }

            var nestNeighbors = 0

            for dy in -1...1 {
                for dx in -1...1 {

                    if dx == 0 && dy == 0 {
                        continue
                    }

                    let nx = x + dx
                    let ny = y + dy

                    guard nx >= 0,
                          nx < width,
                          ny >= 0,
                          ny < height
                    else {
                        continue
                    }

                    let terrain =
                        cells[indexFor(nx, ny)].terrain

                    if terrain == .nest ||
                       terrain == .tunnel {

                        nestNeighbors += 1
                    }
                }
            }

            guard nestNeighbors > 0 else {
                continue
            }

            let pressure =
                Double(nestNeighbors) * 0.004 +
                Double(localAnts) * 0.002

            cells[i].construction =
                min(
                    1.0,
                    cells[i].construction +
                    pressure
                )

            if cells[i].construction >= 1.0 {

                cells[i].terrain =
                    .tunnel

                cells[i].nestStrength =
                    min(
                        1.0,
                        cells[i].nestStrength +
                        0.05
                    )
            }
        }
    }

    // MARK: Pheromone Evaporation

    private func evaporatePheromones() {

        for i in cells.indices {

            cells[i].foodPheromone *= 0.992
            cells[i].nestPheromone *= 0.995

            cells[i].foodPheromone =
                max(
                    0,
                    cells[i].foodPheromone
                )

            cells[i].nestPheromone =
                max(
                    0,
                    cells[i].nestPheromone
                )
        }
    }

    // MARK: Food Cleanup

    private func removeDepletedFood() {

        for source in foodSources {

            guard source.depleted else {
                continue
            }

            let index =
                indexFor(
                    source.x,
                    source.y
                )

            if cells[index].terrain == .food {
                cells[index].terrain =
                    .empty
            }
        }

        foodSources.removeAll {
            $0.depleted
        }
    }

    // MARK: Colony Status

    private func evaluateColony() {

        if ants.isEmpty {

            colonyAlive = false
            return
        }

        // Colony can survive temporarily on individual
        // reserves even when stored colony energy is low.
        let averageEnergy =
            ants.reduce(0.0) {
                $0 + $1.energy
            } /
            Double(ants.count)

        if colonyEnergy <= 0 &&
           averageEnergy < 5 {

            colonyAlive = false
        }
    }

    // MARK: Manual Food

    func addFoodNow() {

        guard foodSources.count < maximumFoodSources else {
            return
        }

        let count =
            max(
                1,
                min(
                    5,
                    ants.count / 250
                )
            )

        for _ in 0..<count {
            createFoodSource()
        }
    }

    // MARK: Statistics

    var averageAntEnergy: Double {

        guard !ants.isEmpty else {
            return 0
        }

        return ants.reduce(0.0) {
            $0 + $1.energy
        } /
        Double(ants.count)
    }

    var totalFoodRemaining: Double {

        foodSources.reduce(0.0) {
            $0 + $1.amount
        }
    }

    var nestCellCount: Int {

        cells.filter {
            $0.terrain == .nest ||
            $0.terrain == .tunnel
        }.count
    }

    var searchingCount: Int {

        ants.filter {
            $0.state == .searching
        }.count
    }

    var returningCount: Int {

        ants.filter {
            $0.state == .returning
        }.count
    }

    var restingCount: Int {

        ants.filter {
            $0.state == .resting
        }.count
    }

    var exploringCount: Int {

        ants.filter {
            $0.state == .exploring
        }.count
    }

    var averageFoodPheromone: Double {

        guard !cells.isEmpty else {
            return 0
        }

        return cells.reduce(0.0) {
            $0 + $1.foodPheromone
        } /
        Double(cells.count)
    }

    var populationBehavior: String {

        let population =
            ants.count

        let active =
            searchingCount +
            returningCount +
            exploringCount

        let activeRatio =
            Double(active) /
            Double(max(population, 1))

        if population < 200 {
            return "Small colony: exploration dominates because few workers are available."
        }

        if activeRatio > 0.80 {
            return "High exploration: most workers are searching for resources."
        }

        if returningCount >
            searchingCount {

            return "Recruitment phase: successful food trails are attracting workers."
        }

        if averageAntEnergy < 20 {
            return "Resource stress: workers are conserving energy and mortality is increasing."
        }

        if foodSources.count > 10 {
            return "Resource-rich environment: multiple food sources are supporting distributed foraging."
        }

        if population > 750 {
            return "Dense colony: local traffic, trail competition, and crowding strongly influence movement."
        }

        return "Established colony: exploration and reinforced foraging trails are competing."
    }

    var populationProgress: Double {

        Double(ants.count) /
        Double(maximumPopulation)
    }

    // MARK: Helpers

    private func indexFor(
        _ x: Int,
        _ y: Int
    ) -> Int {

        y * width + x
    }

    private func distanceFromNest(
        x: Double,
        y: Double
    ) -> Double {

        let dx =
            x -
            Double(nestCenterX)

        let dy =
            y -
            Double(nestCenterY)

        return sqrt(dx * dx + dy * dy)
    }

    private func isInsideNest(
        x: Double,
        y: Double
    ) -> Bool {

        distanceFromNest(
            x: x,
            y: y
        ) <= 6.0
    }

    private func normalized(
        x: Double,
        y: Double
    ) -> (x: Double, y: Double) {

        let magnitude =
            sqrt(x * x + y * y)

        guard magnitude > 0.0001 else {
            return (0, 0)
        }

        return (
            x / magnitude,
            y / magnitude
        )
    }

    private func clamp(
        _ value: Double,
        _ minimum: Double,
        _ maximum: Double
    ) -> Double {

        min(
            maximum,
            max(
                minimum,
                value
            )
        )
    }
}

// MARK: - Content View

@MainActor
struct ContentView: View {

    @StateObject private var simulation =
        AntColonySimulation()

    private let timer =
        Timer.publish(
            every: 0.07,
            on: .main,
            in: .common
        )
        .autoconnect()

    var body: some View {

        VStack(spacing: 10) {

            header

            populationBar

            simulationCanvas

            statistics

            behaviorPanel

            controls
        }
        .padding()
        .onReceive(timer) { _ in

            guard !simulation.paused else {
                return
            }

            simulation.step()
        }
    }

    // MARK: Header

    private var header: some View {

        HStack {

            VStack(
                alignment: .leading,
                spacing: 3
            ) {

                Text("INDIVIDUAL-BASED ANT COLONY")
                    .font(
                        .system(
                            size: 17,
                            weight: .bold,
                            design: .monospaced
                        )
                    )

                Text(
                    "Emergent foraging • pheromone trails • resources • population"
                )
                .font(
                    .system(
                        size: 11,
                        design: .monospaced
                    )
                )
                .foregroundStyle(.secondary)
            }

            Spacer()

            VStack(
                alignment: .trailing,
                spacing: 2
            ) {

                Text(
                    "GEN \(simulation.generation)"
                )
                .font(
                    .system(
                        size: 13,
                        weight: .bold,
                        design: .monospaced
                    )
                )

                Text(
                    simulation.colonyAlive
                    ? "COLONY ACTIVE"
                    : "COLONY FAILED"
                )
                .font(
                    .system(
                        size: 10,
                        weight: .bold,
                        design: .monospaced
                    )
                )
                .foregroundStyle(
                    simulation.colonyAlive
                    ? .green
                    : .red
                )
            }
        }
    }

    // MARK: Population Bar

    private var populationBar: some View {

        VStack(
            alignment: .leading,
            spacing: 4
        ) {

            HStack {

                Text(
                    "WORKERS  \(simulation.ants.count) / \(simulation.maximumPopulation)"
                )

                Spacer()

                Text(
                    "\(simulation.births) births • \(simulation.deaths) deaths"
                )
            }
            .font(
                .system(
                    size: 10,
                    weight: .medium,
                    design: .monospaced
                )
            )

            GeometryReader { geometry in

                ZStack(alignment: .leading) {

                    RoundedRectangle(
                        cornerRadius: 3
                    )
                    .fill(
                        Color.gray.opacity(0.18)
                    )

                    RoundedRectangle(
                        cornerRadius: 3
                    )
                    .fill(
                        Color.green.opacity(0.65)
                    )
                    .frame(
                        width:
                            geometry.size.width *
                            min(
                                1,
                                simulation.populationProgress
                            )
                    )
                }
            }
            .frame(height: 6)
        }
    }

    // MARK: Canvas

    private var simulationCanvas: some View {

        Canvas { context, size in

            let cellWidth =
                size.width /
                CGFloat(simulation.width)

            let cellHeight =
                size.height /
                CGFloat(simulation.height)

            context.fill(
                Path(
                    CGRect(
                        x: 0,
                        y: 0,
                        width: size.width,
                        height: size.height
                    )
                ),
                with: .color(
                    Color(
                        red: 0.025,
                        green: 0.035,
                        blue: 0.025
                    )
                )
            )

            // Environment and pheromone fields.
            for y in 0..<simulation.height {

                for x in 0..<simulation.width {

                    let index =
                        y *
                        simulation.width +
                        x

                    let cell =
                        simulation.cells[index]

                    let rect =
                        CGRect(
                            x:
                                CGFloat(x) *
                                cellWidth,
                            y:
                                CGFloat(y) *
                                cellHeight,
                            width:
                                cellWidth + 0.5,
                            height:
                                cellHeight + 0.5
                        )

                    switch cell.terrain {

                    case .nest:

                        context.fill(
                            Path(rect),
                            with:
                                .color(
                                    Color(
                                        red: 0.38,
                                        green: 0.22,
                                        blue: 0.10
                                    )
                                )
                        )

                    case .tunnel:

                        context.fill(
                            Path(rect),
                            with:
                                .color(
                                    Color(
                                        red: 0.23,
                                        green: 0.15,
                                        blue: 0.08
                                    )
                                )
                        )

                    case .obstacle:

                        context.fill(
                            Path(rect),
                            with:
                                .color(
                                    Color.gray.opacity(0.42)
                                )
                        )

                    case .food:

                        context.fill(
                            Path(rect),
                            with:
                                .color(
                                    Color.green.opacity(0.20)
                                )
                        )

                    case .empty:

                        if cell.foodPheromone > 0.08 {

                            let opacity =
                                min(
                                    0.32,
                                    cell.foodPheromone /
                                    30.0
                                )

                            context.fill(
                                Path(rect),
                                with:
                                    .color(
                                        Color.orange
                                            .opacity(opacity)
                                    )
                            )
                        }

                        if cell.nestPheromone > 0.08 {

                            let opacity =
                                min(
                                    0.18,
                                    cell.nestPheromone /
                                    40.0
                                )

                            context.fill(
                                Path(rect),
                                with:
                                    .color(
                                        Color.brown
                                            .opacity(opacity)
                                    )
                            )
                        }
                    }
                }
            }

            // Food sources.
            for food in simulation.foodSources {

                let x =
                    CGFloat(food.x) *
                    cellWidth +
                    cellWidth / 2

                let y =
                    CGFloat(food.y) *
                    cellHeight +
                    cellHeight / 2

                let radius =
                    max(
                        3,
                        min(
                            9,
                            3 +
                            food.amount / 15
                        )
                    )

                let rect =
                    CGRect(
                        x: x - radius,
                        y: y - radius,
                        width: radius * 2,
                        height: radius * 2
                    )

                context.fill(
                    Path(
                        ellipseIn: rect
                    ),
                    with:
                        .color(
                            foodColor(
                                food.type
                            )
                        )
                )
            }

            // Every ant is rendered individually.
            let antRadius =
                simulation.ants.count > 750
                ? 1.25
                : 1.7

            for ant in simulation.ants {

                let x =
                    CGFloat(ant.x) *
                    cellWidth +
                    cellWidth / 2

                let y =
                    CGFloat(ant.y) *
                    cellHeight +
                    cellHeight / 2

                let radius =
                    CGFloat(antRadius)

                let rect =
                    CGRect(
                        x: x - radius,
                        y: y - radius,
                        width: radius * 2,
                        height: radius * 2
                    )

                context.fill(
                    Path(
                        ellipseIn: rect
                    ),
                    with:
                        .color(
                            antColor(
                                ant.state
                            )
                        )
                )

                // Tiny heading marker makes individual motion visible.
                let directionLength: CGFloat = 3.0

                var path = Path()

                path.move(
                    to:
                        CGPoint(
                            x: x,
                            y: y
                        )
                )

                path.addLine(
                    to:
                        CGPoint(
                            x:
                                x +
                                CGFloat(
                                    ant.directionX
                                ) *
                                directionLength,
                            y:
                                y +
                                CGFloat(
                                    ant.directionY
                                ) *
                                directionLength
                        )
                )

                context.stroke(
                    path,
                    with:
                        .color(
                            Color.white.opacity(0.35)
                        ),
                    lineWidth: 0.5
                )
            }
        }
        .frame(
            minHeight: 420
        )
        .clipShape(
            RoundedRectangle(
                cornerRadius: 10
            )
        )
        .overlay(
            RoundedRectangle(
                cornerRadius: 10
            )
            .stroke(
                Color.white.opacity(0.12),
                lineWidth: 1
            )
        )
    }

    // MARK: Statistics

    private var statistics: some View {

        LazyVGrid(
            columns: [
                GridItem(.flexible()),
                GridItem(.flexible()),
                GridItem(.flexible()),
                GridItem(.flexible())
            ],
            spacing: 6
        ) {

            statCard(
                title: "COLONY ENERGY",
                value:
                    String(
                        format: "%.0f",
                        simulation.colonyEnergy
                    )
            )

            statCard(
                title: "FOOD STORED",
                value:
                    String(
                        format: "%.0f",
                        simulation.totalFoodRemaining
                    )
            )

            statCard(
                title: "FOOD SOURCES",
                value:
                    "\(simulation.foodSources.count)"
            )

            statCard(
                title: "AVG ANT ENERGY",
                value:
                    String(
                        format: "%.1f",
                        simulation.averageAntEnergy
                    )
            )

            statCard(
                title: "SEARCHING",
                value:
                    "\(simulation.searchingCount)"
            )

            statCard(
                title: "RETURNING",
                value:
                    "\(simulation.returningCount)"
            )

            statCard(
                title: "RESTING",
                value:
                    "\(simulation.restingCount)"
            )

            statCard(
                title: "EXPLORING",
                value:
                    "\(simulation.exploringCount)"
            )
        }
    }

    private func statCard(
        title: String,
        value: String
    ) -> some View {

        VStack(
            spacing: 3
        ) {

            Text(title)
                .font(
                    .system(
                        size: 8,
                        weight: .medium,
                        design: .monospaced
                    )
                )
                .foregroundStyle(.secondary)

            Text(value)
                .font(
                    .system(
                        size: 14,
                        weight: .bold,
                        design: .monospaced
                    )
                )
        }
        .frame(
            maxWidth: .infinity,
            minHeight: 42
        )
        .background(
            Color.gray.opacity(0.10)
        )
        .clipShape(
            RoundedRectangle(
                cornerRadius: 6
            )
        )
    }

    // MARK: Behavior

    private var behaviorPanel: some View {

        VStack(
            alignment: .leading,
            spacing: 5
        ) {

            Text("EMERGENT COLONY BEHAVIOR")
                .font(
                    .system(
                        size: 10,
                        weight: .bold,
                        design: .monospaced
                    )
                )

            Text(
                simulation.populationBehavior
            )
            .font(
                .system(
                    size: 11,
                    design: .monospaced
                )
            )

            Text(
                "Pheromone: " +
                String(
                    format: "%.3f",
                    simulation.averageFoodPheromone
                ) +
                "    Nest/tunnels: " +
                "\(simulation.nestCellCount)" +
                "    Food collected: " +
                String(
                    format: "%.0f",
                    simulation.foodCollected
                )
            )
            .font(
                .system(
                    size: 9,
                    design: .monospaced
                )
            )
            .foregroundStyle(.secondary)
        }
        .frame(
            maxWidth: .infinity,
            alignment: .leading
        )
        .padding(8)
        .background(
            Color.gray.opacity(0.08)
        )
        .clipShape(
            RoundedRectangle(
                cornerRadius: 7
            )
        )
    }

    // MARK: Controls

    private var controls: some View {

        HStack {

            Button(
                simulation.paused
                ? "RUN"
                : "PAUSE"
            ) {

                simulation.paused.toggle()
            }

            Button("STEP") {

                simulation.step()
            }

            Button("ADD FOOD") {

                simulation.addFoodNow()
            }

            Spacer()

            Text(
                "250 initial workers • 1:1 individual agents • max 1000"
            )
            .font(
                .system(
                    size: 9,
                    design: .monospaced
                )
            )
            .foregroundStyle(.secondary)
        }
        .buttonStyle(.bordered)
    }

    // MARK: Colors

    private func foodColor(
        _ type: FoodType
    ) -> Color {

        switch type {

        case .seed:
            return .green

        case .fruit:
            return .red

        case .insect:
            return .purple

        case .nectar:
            return .yellow
        }
    }

    private func antColor(
        _ state: AntState
    ) -> Color {

        switch state {

        case .searching:
            return .white

        case .returning:
            return .orange

        case .resting:
            return .gray

        case .exploring:
            return .yellow
        }
    }
}

// MARK: - Preview

#Preview {
    ContentView()
}
